@host= http://localhost:5189

Get {{host}}/dinners 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjE1N2UzZC0zMjQxLTQ0NTgtOTM3MC02ZjBjMmQxNTRlNTUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMzdjZjAxMTgtOTg4My00MGZhLWI4MGUtN2Y0ZTJjNmE2NjJjIiwiZXhwIjoxNjk3NDczODc4LCJpc3MiOiJTU19STVMiLCJhdWQiOiJTU19STVMifQ._tvTkkaFsUFz_r7YB0DUGZtLJrjHOdzd3AuOyeN-XUk