@host= http://localhost:5189

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJBMTI4Q0JDLUhTMjU2IiwidHlwIjoiSldUIn0.eyJzdWIiOiJmMzRiMWYxYS03ZTI4LTRmMDAtOWEzNi1mNjdlZGI0Mjk3M2EiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiOTZhMGNjMDMtMjQ3OC00YWZjLWFkNzQtOGM0YTc1OTMyYTY0IiwiZXhwIjoxNjk2ODYxNjY3LCJpc3MiOiJTU19STVMiLCJhdWQiOiJTU19STVMifQ.OcwGZWFsupZZbnUwRIq01h-LqFw9Wgh_xuVUIObLh5s