@host= http://localhost:5189

GET {{host}}/dinners

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjcxZWM1OC1iYjczLTQwMjUtOGI4ZC1hNTg4NmI0YTFlNzEiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMWZlMmE2MTUtNDI4Mi00NTVkLTgxNGItYjVkMjY2MWY4ODAzIiwiZXhwIjoxNjk2ODY2Mjg1LCJpc3MiOiJTU19STVMiLCJhdWQiOiJTU19STVMifQ.8c5qN7lHqzwKsEFW03oJdeB8_p0h0OQERMEFOS8llPE