@host= http://localhost:5189

POST {{host}}/auth/register HTTP/1.1
content-type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "jsds.doe@example.com",
  "password": "Psw@1234"
}