// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartRMS.Domain.ModelSignOn;

public partial class SysUser
{
    public string UserId { get; set; }

    public string UserName { get; set; }

    public string UserCode { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool? Active { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public DateTime? LastLogin { get; set; }
}