// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartRMS.Domain.Models;

public partial class BillInvocie
{
    public string InvoiceId { get; set; }

    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string CustomerId { get; set; }

    public string StoreId { get; set; }

    public decimal? TotalCost { get; set; }

    public decimal? TotalOtherAmount { get; set; }

    public decimal? TotalPay { get; set; }

    public decimal? TotalCreditPay { get; set; }

    public decimal? Remain { get; set; }

    public bool Active { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime ModifiedOn { get; set; }
}