// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartRMS.Domain.Models;

public partial class MasItemUnit
{
    public string UnitId { get; set; }

    public string UnitName { get; set; }

    public string Price { get; set; }

    public string Barcode { get; set; }

    public string ItemId { get; set; }

    public bool? ItLowerUnit { get; set; }

    public decimal? ConvertQty { get; set; }
}