// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartRMS.Domain.Models;

public partial class MasMenuUnit
{
    public string UnitId { get; set; }

    public string MenuId { get; set; }

    public string UnitLabel { get; set; }

    public decimal? Price { get; set; }

    public string Barcode { get; set; }

    public string Qrcode { get; set; }

    public bool Active { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime ModifiedOn { get; set; }
}