// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartRMS.Domain.Models;

public partial class MasStore
{
    public string StoreId { get; set; }

    public string StoreName { get; set; }

    public string Location { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public bool IsSaleStore { get; set; }

    public string ManagerName { get; set; }

    public bool Active { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string CreatedDate { get; set; }
}