// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartRMS.Domain.Models;

public partial class MasTabelView
{
    public string TableId { get; set; }

    public string TableName { get; set; }

    public string TableNo { get; set; }

    public string Location { get; set; }

    public bool Active { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime ModifiedOn { get; set; }

    public string CreatedByCode { get; set; }

    public string ModifiedByCode { get; set; }

    public string Status { get; set; }
}