// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartRMS.Domain.Models;

public partial class Smart_RMSContext : DbContext
{
    public Smart_RMSContext(DbContextOptions<Smart_RMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MasTabel> MasTabel { get; set; }

    public virtual DbSet<MasTabelView> MasTabelView { get; set; }

    public virtual DbSet<SysUserView> SysUserView { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MasTabel>(entity =>
        {
            entity.HasKey(e => e.TableId);

            entity.ToTable("Mas_Tabel");

            entity.Property(e => e.TableId)
                .HasMaxLength(50)
                .HasColumnName("TableID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.TableNo).HasMaxLength(100);
        });

        modelBuilder.Entity<MasTabelView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Mas_TabelView");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedByCode).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedByCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.TableId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("TableID");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.TableNo).HasMaxLength(100);
        });

        modelBuilder.Entity<SysUserView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Sys_UserView");

            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.LastLogin).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.UserCode).HasMaxLength(50);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("UserID");
            entity.Property(e => e.UserName).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}