// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartRMS.Domain.Models;

public partial class Smart_RMSContext : DbContext
{
    public Smart_RMSContext(DbContextOptions<Smart_RMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BillInvocie> BillInvocie { get; set; }

    public virtual DbSet<MasCategory> MasCategory { get; set; }

    public virtual DbSet<MasCategoryView> MasCategoryView { get; set; }

    public virtual DbSet<MasCustomer> MasCustomer { get; set; }

    public virtual DbSet<MasCustomerView> MasCustomerView { get; set; }

    public virtual DbSet<MasMenu> MasMenu { get; set; }

    public virtual DbSet<MasMenuUnit> MasMenuUnit { get; set; }

    public virtual DbSet<MasMenuUnitView> MasMenuUnitView { get; set; }

    public virtual DbSet<MasMenuView> MasMenuView { get; set; }

    public virtual DbSet<MasStore> MasStore { get; set; }

    public virtual DbSet<MasStoreView> MasStoreView { get; set; }

    public virtual DbSet<MasTabel> MasTabel { get; set; }

    public virtual DbSet<MasTabelView> MasTabelView { get; set; }

    public virtual DbSet<SysUserView> SysUserView { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BillInvocie>(entity =>
        {
            entity.HasKey(e => e.InvoiceId);

            entity.ToTable("Bill_Invocie");

            entity.Property(e => e.InvoiceId)
                .HasMaxLength(50)
                .HasColumnName("InvoiceID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .HasColumnName("CustomerID");
            entity.Property(e => e.InvoiceDate).HasColumnType("datetime");
            entity.Property(e => e.InvoiceNo).HasMaxLength(50);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Remain).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.StoreId)
                .HasMaxLength(50)
                .HasColumnName("StoreID");
            entity.Property(e => e.TotalCost).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.TotalCreditPay).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.TotalOtherAmount).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.TotalPay).HasColumnType("decimal(18, 0)");
        });

        modelBuilder.Entity<MasCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.ToTable("Mas_Category");

            entity.Property(e => e.CategoryId)
                .HasMaxLength(50)
                .HasColumnName("CategoryID");
            entity.Property(e => e.CategoryIcon).HasMaxLength(50);
            entity.Property(e => e.CategoryName).HasMaxLength(50);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<MasCategoryView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Mas_CategoryView");

            entity.Property(e => e.CategoryIcon).HasMaxLength(50);
            entity.Property(e => e.CategoryId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName).HasMaxLength(50);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedByCode).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedByCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<MasCustomer>(entity =>
        {
            entity.HasKey(e => e.CustomerId);

            entity.ToTable("Mas_Customer");

            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .HasColumnName("CustomerID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.CustomerName).HasMaxLength(100);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhoneNo).HasMaxLength(50);
        });

        modelBuilder.Entity<MasCustomerView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Mas_CustomerView");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedByCode).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.CustomerId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("CustomerID");
            entity.Property(e => e.CustomerName).HasMaxLength(100);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedByCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhoneNo).HasMaxLength(50);
        });

        modelBuilder.Entity<MasMenu>(entity =>
        {
            entity.HasKey(e => e.MenuId);

            entity.ToTable("Mas_Menu");

            entity.Property(e => e.MenuId)
                .HasMaxLength(50)
                .HasColumnName("MenuID");
            entity.Property(e => e.CategoryId)
                .HasMaxLength(50)
                .HasColumnName("CategoryID");
            entity.Property(e => e.CookingTime).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.IsNeedCook).HasColumnName("isNeedCook");
            entity.Property(e => e.IsSubMenuId).HasColumnName("isSubMenuID");
            entity.Property(e => e.MenuCode).HasMaxLength(50);
            entity.Property(e => e.MenuName).HasMaxLength(100);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhotoUrl)
                .HasMaxLength(100)
                .HasColumnName("PhotoURL");
        });

        modelBuilder.Entity<MasMenuUnit>(entity =>
        {
            entity.HasKey(e => e.UnitId).HasName("PK_Mas_MenuUnit]");

            entity.ToTable("Mas_MenuUnit");

            entity.Property(e => e.UnitId)
                .HasMaxLength(50)
                .HasColumnName("UnitID");
            entity.Property(e => e.Barcode).HasMaxLength(50);
            entity.Property(e => e.ConvertQty)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("ConvertQTY");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ItLowerUnit).HasColumnName("itLowerUnit");
            entity.Property(e => e.MenuId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("MenuID");
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Qrcode)
                .HasMaxLength(50)
                .HasColumnName("QRCode");
            entity.Property(e => e.UnitLabel).HasMaxLength(50);
        });

        modelBuilder.Entity<MasMenuUnitView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Mas_MenuUnitView");

            entity.Property(e => e.Barcode).HasMaxLength(50);
            entity.Property(e => e.CategoryId)
                .HasMaxLength(50)
                .HasColumnName("CategoryID");
            entity.Property(e => e.ConvertQty)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("ConvertQTY");
            entity.Property(e => e.CookingTime).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedByCode).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.IsNeedCook).HasColumnName("isNeedCook");
            entity.Property(e => e.IsSubMenuId).HasColumnName("isSubMenuID");
            entity.Property(e => e.ItLowerUnit).HasColumnName("itLowerUnit");
            entity.Property(e => e.MenuCode).HasMaxLength(50);
            entity.Property(e => e.MenuId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("MenuID");
            entity.Property(e => e.MenuName).HasMaxLength(100);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedByCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhotoUrl)
                .HasMaxLength(100)
                .HasColumnName("PhotoURL");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Qrcode)
                .HasMaxLength(50)
                .HasColumnName("QRCode");
            entity.Property(e => e.UnitId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("UnitID");
            entity.Property(e => e.UnitLabel).HasMaxLength(50);
        });

        modelBuilder.Entity<MasMenuView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Mas_MenuView");

            entity.Property(e => e.CategoryIcon).HasMaxLength(50);
            entity.Property(e => e.CategoryId)
                .HasMaxLength(50)
                .HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName).HasMaxLength(50);
            entity.Property(e => e.CookingTime).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedByCode).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.IsNeedCook).HasColumnName("isNeedCook");
            entity.Property(e => e.IsSubMenuId).HasColumnName("isSubMenuID");
            entity.Property(e => e.MenuCode).HasMaxLength(50);
            entity.Property(e => e.MenuId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("MenuID");
            entity.Property(e => e.MenuName).HasMaxLength(100);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedByCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhotoUrl)
                .HasMaxLength(100)
                .HasColumnName("PhotoURL");
        });

        modelBuilder.Entity<MasStore>(entity =>
        {
            entity.HasKey(e => e.StoreId);

            entity.ToTable("Mas_Store");

            entity.Property(e => e.StoreId).HasMaxLength(50);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(200);
            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.ManagerName).HasMaxLength(200);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhoneNumber).HasMaxLength(100);
            entity.Property(e => e.StoreName)
                .IsRequired()
                .HasMaxLength(300);
        });

        modelBuilder.Entity<MasStoreView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Mas_StoreView");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedByCode).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(200);
            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.ManagerName).HasMaxLength(200);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedByCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhoneNumber).HasMaxLength(100);
            entity.Property(e => e.StoreId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StoreName)
                .IsRequired()
                .HasMaxLength(300);
        });

        modelBuilder.Entity<MasTabel>(entity =>
        {
            entity.HasKey(e => e.TableId);

            entity.ToTable("Mas_Tabel");

            entity.Property(e => e.TableId)
                .HasMaxLength(50)
                .HasColumnName("TableID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.TableNo).HasMaxLength(100);
        });

        modelBuilder.Entity<MasTabelView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Mas_TabelView");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedByCode).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.ModifiedBy)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedByCode).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TableId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("TableID");
            entity.Property(e => e.TableName).HasMaxLength(100);
            entity.Property(e => e.TableNo).HasMaxLength(100);
        });

        modelBuilder.Entity<SysUserView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("Sys_UserView");

            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.LastLogin).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.UserCode).HasMaxLength(50);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("UserID");
            entity.Property(e => e.UserName).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}